/**
 * Deterministic, accessible chart color system.
 *
 * - Named categories always get the same color across views and page reloads.
 * - If the category isn't in the base palette, a color is generated by hashing
 *   the name into the HSL color space with consistent saturation/lightness so
 *   it stays visually distinct and accessible.
 * - No fallback to a single grey — every category gets a real color.
 */

// Base palette — 14 visually distinct, accessible colors
const BASE_PALETTE: Record<string, string> = {
  // Department names
  "Education":           "hsl(195, 70%, 34%)",
  "Public Safety":       "hsl(24, 70%, 50%)",
  "Public Works":        "hsl(160, 45%, 38%)",
  "Parks & Recreation":  "hsl(120, 40%, 42%)",
  "Administration":      "hsl(220, 35%, 50%)",
  "Social Services":     "hsl(340, 50%, 45%)",
  "Library":             "hsl(45, 80%, 48%)",
  "Health":              "hsl(280, 45%, 50%)",
  "Transportation":      "hsl(200, 60%, 40%)",
  "Housing":             "hsl(30, 65%, 44%)",
  "Planning":            "hsl(240, 40%, 52%)",
  "Finance":             "hsl(170, 50%, 36%)",
  "Information Technology": "hsl(210, 55%, 46%)",
  "Human Resources":     "hsl(355, 55%, 48%)",
  // Revenue category names
  "Property Taxes":      "hsl(195, 70%, 34%)",
  "State Aid":           "hsl(24, 70%, 50%)",
  "Fees":                "hsl(160, 45%, 38%)",
  "Grants":              "hsl(45, 80%, 48%)",
  "Other":               "hsl(220, 35%, 50%)",
  "Federal Aid":         "hsl(280, 45%, 50%)",
  "Local Receipts":      "hsl(120, 40%, 42%)",
  "Taxes":               "hsl(195, 70%, 34%)",
  "Intergovernmental":   "hsl(200, 60%, 40%)",
};

/**
 * A fast string hash → integer. Used to deterministically derive a hue from a
 * category name that isn't in the base palette.
 */
function hashString(str: string): number {
  let h = 5381;
  for (let i = 0; i < str.length; i++) {
    h = ((h << 5) + h) ^ str.charCodeAt(i);
    h = h >>> 0; // keep as unsigned 32-bit
  }
  return h;
}

/**
 * Returns a deterministic HSL color for any category/department string.
 * Known names → curated palette. Unknown names → generated from hash.
 */
export function getCategoryColor(name: string): string {
  if (BASE_PALETTE[name]) return BASE_PALETTE[name];
  // Generate: spread hues at golden-ratio intervals starting from the hash
  const hash = hashString(name);
  const hue = Math.round((hash * 137.508) % 360); // golden angle spreading
  const sat = 45 + (hash % 20);                    // 45–64% saturation
  const lgt = 38 + (hash % 16);                    // 38–53% lightness
  return `hsl(${hue}, ${sat}%, ${lgt}%)`;
}

/** Alias for department names (same logic). */
export const getDeptColor = getCategoryColor;
